### PR TITLE
Add Mapping ISO-19139_che to DCAT-AP Switzerland Documentation

### PR DESCRIPTION
**Pull request by scorewinner**

### CODE REVIEW

**Comment by loleg** [comment]
Formatting and otherwise the document looks good to me, though without experience in applying this standard it's hard for me to understand in what part of the publication process it is actually relevant. And I think that the main function of the Handbook is to be a place to explain that :) 

So I would suggest adding links in the [DCAT-AP article](https://handbook.opendata.swiss/library/ch-dcat-ap.html) - perhaps under a new headline, like Complementary Standards, with a short explanation of why this is helpful. 

Furthermore, while the Library is an important holding place for technical documentation, it is important that its contents are referenced within the introductory sections of the OGD Handbook. @scorewinner  do you see a good place for such a reference, in the form of a very simple explanation of how this fits into a workflow, already?

**Comment by metaodi** [comment]
@loleg I definitely think it should be crossreferenced in the "Geocat" chapter here: https://handbook.opendata.swiss/de/publish/swiss#geoadmin

Note that this documentation will be completed (e.g. the currently empty "Description" field) by someone from geo.admin.ch/geocat.

**Comment by loleg** [comment]
Looks good @taniahumar - just, please add a language extension to the file, i.e. change from `iso-19139-che-dcat.md` to `iso-19139-che-dcat.en.md`

**Comment by davidoesch** [comment]
any ETA here?

**Comment by JPLovato** [comment]
Hi guys, thank you for you contribution. My team will check it asap - we've quite a lot going on with the portal right now. Thank you for your patience

**Comment by loleg** [comment]
Merging with minor formatting fixes and approval from @JPLovato

**Pull request merged**
